version: 2.1

jobs:
  build-and-test:

    steps:
      - checkout
      - run:
          name: build
          command: |
            docker build -t django-app .

workflows:
  django-ci:
    jobs:
      - build-and-test
