version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable   # Required executor

    steps:
      - checkout

      - setup_remote_docker       # Needed for Docker build

      - run:
          name: Build Docker Image
          command: |
            docker build -t django-app .

workflows:
  django-integration:
    jobs:
      - build-and-test
